Minor npc_zombie improvements
mapbase-source/source-sdk-2013 pull request #312
Opened 2024-07-28 13:05 UTC by Wikot235

-Added a keyvalue that changes zombie melee attack range
-Added a spawnflag that disables spawning a headcrab when a zombie dies

---

#### PR Checklist
- [x] **My PR follows all guidelines in the CONTRIBUTING.md file**
- [x] My PR targets a `develop` branch OR targets another branch with a specific goal in mind

2025-01-04 13:19 UTC, Blixibon requested changes

2025-01-04 13:19 UTC, Blixibon commented on sp/src/game/server/hl2/npc_BaseZombie.h
> -#define ZOMBIE_MELEE_REACH	55
I noticed `m_flMeleeReach` does not initialize with the old melee reach of `55`. Wouldn't this break existing zombies that don't specify the new keyvalue?

2025-01-05 15:07 UTC, Wikot235 commented on sp/src/game/server/hl2/npc_BaseZombie.h
> -#define ZOMBIE_MELEE_REACH	55
Yeah, that's an oversight on my end. Thanks for pointing that out.

2025-01-09 13:40 UTC, Blixibon approved these changes

2025-01-09 19:15 UTC, merged